---
version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/datass
      - ./db:/docker-entrypoint-initdb.d/
    healthcheck:
      interval: 5s
      retries: 10
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  etl:
    container_name: etl
    build:
      context: ./etl
      args:
        PG_DB: ${PG_DB}
        PG_USER: ${PG_USER}
        PG_HOST: ${PG_HOST}
        PG_PW: ${PG_PW}
        REPO: ${REPO}
    depends_on:
      db:
        condition: service_healthy
        restart: true
    restart: on-failure:10
  notebook:
    container_name: notebook
    build:
      context: ./notebook
      args:
        PG_DB: ${PG_DB}
        PG_USER: ${PG_USER}
        PG_HOST: ${PG_HOST}
        PG_PW: ${PG_PW}
        JUPYTER_TOKEN: ${NOTEBOOK_PW}
        DOCKER_STACKS_JUPYTER_CMD: notebook
    ports:
      - "8888:8888"
